FROM python:3.11-slim-bullseye

# Install poetry
# See https://python-poetry.org/docs/#ci-recommendations
ENV POETRY_HOME /opt/poetry
ENV POETRY_VERSION 1.3.1
RUN python3 -m venv $POETRY_HOME; \
    $POETRY_HOME/bin/pip install poetry==$POETRY_VERSION
ENV PATH $POETRY_HOME/bin:$PATH

WORKDIR /app

# Install dependencies into a virtual environment
# hadolint global ignore=SC1091
COPY pyproject.toml poetry.lock ./
RUN python3 -m venv --copies /app/venv; \
    source venv/bin/activate; \
    poetry install --no-root --no-interaction --with dev
ENV PATH /app/venv/bin:$PATH

COPY pyside6_playground pyside6_playground
COPY tests tests

ENV ENV dev
ENV APP_ENV $ENV

CMD ["poetry", "run", "pytest", "--cov-report", "term-missing", "--cov=pyside6_playground", "--typeguard-packages=pyside6_playground"]
